build: fix the compilation of LinkedHashSet with GCC
Cherry-pick Chromium commit 489158d82ae86d0b31694141d2d799bd240e14f8.

Currently the compilation fails:

../../third_party/WebKit/Source/platform/wtf/LinkedHashSet.h: In member function ‘void WTF::LinkedHashSet<Value, HashFunctions, HashTraits, Allocator>::Swap(WTF::LinkedHashSet<Value, HashFunctions, HashTraits, Allocator>&)’:
../../third_party/WebKit/Source/platform/wtf/LinkedHashSet.h:691:3: error: there are no arguments to ‘SwapAnchor’ that depend on a template parameter, so a declaration of ‘SwapAnchor’ must be available [-fpermissive]
   SwapAnchor(anchor_, other.anchor_);
   ^~~~~~~~~~
../../third_party/WebKit/Source/platform/wtf/LinkedHashSet.h:691:3: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)

ninja: build stopped: subcommand failed.

To fix it move the SwapAnchor and swap declaration before the templates
block (above the first SwapAnchor call).

Change-Id: Idd902ef00f0165d157dee886406f6be78191f80b
Reviewed-on: https://chromium-review.googlesource.com/616563
Reviewed-by: Yuta Kitamura <yutak@chromium.org>
Commit-Queue: Yuta Kitamura <yutak@chromium.org>
Cr-Commit-Position: refs/heads/master@{#494751}